name: GitHub Workflow Initiation

on:
  push:
    branches:
      - master

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Display event trigger
        run: |
          echo "This job was automatically triggered by ${{ github.event_name }}"

      - name: Display operating system
        run: |
          echo "Operating System: ${{ runner.os }}"

      - name: Display repository URL
        run: |
          echo "Repository URL: https://github.com/${{ github.repository }}"

      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Display cloned repository
        run: |
          echo "The repository ${{ github.repository }} has been successfully cloned."

      - name: List files in the repository
        run: |
          ls -l ${{ github.workspace }}

      - name: Display job status
        run: |
          echo "Job status is ${{ job.status }}"
