name: Liquibase Update

on:
  push:
    branches:
      - master

jobs:
  liquibase_update:
    name: Liquibase Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Liquibase Update
        uses: liquibase/liquibase-github-action@v7
        with:
          operation: 'update'
          classpath: 'src/main/resources/liquibase'
          changeLogFile: 'db-changelog-master.xml'
          username: ${{ secrets.DATABASE_USERNAME }}
          password: ${{ secrets.DATABASE_PASSWORD }}
          url: ${{ secrets.DATABASE_URL }}